version: '3'

services:
  mysql:
    container_name: gofood-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gofood

  redis:
    container_name: gofood-redis
    image: redis:6
    command: redis-server --requirepass redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6379:6379"
    networks:
      - gofood

networks:
  gofood:

volumes:
  mysql_data:
  redis_data: